### ISSUE TITLE
Blank notes

### ISSUE THREAD

**Issue by alexjj** [akhater/Daily-Notes-for-TW5#1]
Hello,

I added the plugin from [here](https://akhater.github.io/drift/#Plugin%20-%20Daily%20Notes). 

When I enter something it creates the timestamp but no text appears.

![image](https://user-images.githubusercontent.com/440939/83390611-12204180-a3ea-11ea-8b77-d002a6e84f2c.png)

The Daily Capture tiddler is: `{{$:/ak/plugins/DailyNotes/ui/capture}}`

**Comment by akhater** [comment]
Hi Alex

is it possible to give me access to the TW file so i can test it ? I tried it on a blank TW and it worked fine

thank you

**Comment by alexjj** [comment]
[Here you go](https://send.firefox.com/download/ba0803a569244673/#6nPEjWAuCbyfawE4m-yK2g)

**Comment by akhater** [comment]
Thanks for that

the first thing I notice is that you are running 5.1.19 and I using the trim[] operator that does't exist in versions previous to 5.1.20

thank you for letting me know

**Comment by alexjj** [comment]
that'll do it. thanks.
